server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5              #拉取服务时间
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka    #注册到eureka注册中心
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/**              #商品微服务的映射路径
  ignored-services:
    - upload-service      #忽略某个微服务